<meta name="google-site-verification" content="yChs9SYO9StPknt31jku93Rq1j5V8WQXG57jUGC2ybw" />

google-site-verification: google705e8f2b38ba157e.html

theme: jekyll-theme-tactile
title: "MASMC 2019"
description: "Mid-Atlantic States Mycological Conference @ The University of Tennessee"
plugins:
- jekyll-seo-tag


